---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: datascienceclusters.datasciencecluster.opendatahub.io
spec:
  group: datasciencecluster.opendatahub.io
  names:
    kind: DataScienceCluster
    listKind: DataScienceClusterList
    plural: datascienceclusters
    singular: datasciencecluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DataScienceCluster is the Schema for the datascienceclusters
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DataScienceClusterSpec defines the desired state of DataScienceCluster
            properties:
              components:
                description: Components is used to override and fine tune specific
                  component configurations.
                properties:
                  dashboard:
                    description: Dashboard component configuration
                    properties:
                      enabled:
                        description: enables or disables the component. A disabled
                          component will not be installed.
                        type: boolean
                      replicas:
                        description: number of replicas to deploy for the component
                        format: int64
                        type: integer
                      resources:
                        description: resources to allocate to the component
                        properties:
                          limits:
                            additionalProperties:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            description: 'Limits describes the maximum amount of compute
                              resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                            type: object
                          requests:
                            additionalProperties:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            description: 'Requests describes the minimum amount of
                              compute resources required. If Requests is omitted for
                              a container, it defaults to Limits if that is explicitly
                              specified, otherwise to an implementation-defined value.
                              More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                            type: object
                        type: object
                    type: object
                  dataServicePipeline:
                    description: DataServicePipeline component configuration
                    properties:
                      enabled:
                        description: enables or disables the component. A disabled
                          component will not be installed.
                        type: boolean
                      replicas:
                        description: number of replicas to deploy for the component
                        format: int64
                        type: integer
                      resources:
                        description: resources to allocate to the component
                        properties:
                          limits:
                            additionalProperties:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            description: 'Limits describes the maximum amount of compute
                              resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                            type: object
                          requests:
                            additionalProperties:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            description: 'Requests describes the minimum amount of
                              compute resources required. If Requests is omitted for
                              a container, it defaults to Limits if that is explicitly
                              specified, otherwise to an implementation-defined value.
                              More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                            type: object
                        type: object
                    type: object
                type: object
              profile:
                description: 'A profile sets the default components and configuration
                  to install for a given use case. The profile configuration can still
                  be overriden by the user on a per component basis. If not defined,
                  the ''full'' profile is used. Valid values are: - full: all components
                  are installed - serving: only serving components are installed -
                  training: only training components are installed - workbench: only
                  workbench components are installed'
                type: string
            type: object
          status:
            description: DataScienceClusterStatus defines the observed state of DataScienceCluster
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
